title: Cosmic Awesome Page
author: Cosmic
email: noneofyourbusiness@mememail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a demo site that will appear in the meta for Google search results.
  Hi Google :) (and hi feed.xml too)
  
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  cosmic-codes # DO NOT include the @ character, or else the build will fail!
# LI?

show_excerpts: true # set to false to remove excerpts on the homepage
